Repository waku-org/nwaku, pull requests merged in 2022-09, with the labels that each got.

#1104 chore(noise): minor refactor of default checks of keypairs
  waku/v2/protocol/waku_noise/noise_handshake_processing.nim
  waku/v2/protocol/waku_noise/noise_utils.nim
Labels: track:maintenance

#1107 refactor(wakunode2): add convenience methods for adding protocol peers
  waku/v2/node/wakunode2.nim
Labels: track:maintenance

#1109 chore(waku-store): improve logging and query traceability
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1108 refactor(wakunode2): deprecate non-async protocol api methods
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1120 fix(waku-store): added an index to improve messages query time
  waku/v2/node/storage/message/waku_message_store_queries.nim
  waku/v2/node/storage/migration/migration_types.nim
  waku/v2/node/storage/migration/migrations_scripts/message/00005_updateIndex.up.sql
Labels: track:production

#1118 chore(chat2): selection of store node at random
  examples/v2/chat2.nim
Labels: track:maintenance

#1121 refactor(wakunode): split peer utils tests into a new file
  tests/all_tests_v2.nim
  tests/v2/test_utils_peers.nim
  tests/v2/test_wakunode.nim
Labels: track:maintenance

#1122 refactor(wakunode): split wakunode rln-relay tests into a new file
  tests/all_tests_v2.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_rln_relay.nim
Labels: track:maintenance

#1126 chore(wakunode): collocate wakuswitch file to the depending modules
  waku/v2/node/wakunode2.nim
  waku/v2/node/wakuswitch.nim
Labels: track:maintenance

#1124 refactor(wakunode): split wakunode lightpush tests into a new file
  tests/all_tests_v2.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_lightpush.nim
Labels: track:maintenance

#1132 refactor(wakunode): split wakunode filter tests into a new file
  tests/all_tests_v2.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_filter.nim
Labels: track:maintenance

#1136 fix(store): add a table index to improve message insertion time
  waku/v2/node/storage/message/waku_message_store.nim
  waku/v2/node/storage/message/waku_message_store_queries.nim
  waku/v2/node/storage/migration/migrations_scripts/message/00005_updateIndex.up.sql
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1135 refactor(wakunode): split wakunode store tests into a new file
  tests/all_tests_v2.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_store.nim
Labels: track:maintenance

#1138 refactor(wakunode): split wakunode relay tests into a new file
  tests/all_tests_v2.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_relay.nim
Labels: track:maintenance

#1143 chore(utils): remove unused types and methods
  waku/v2/utils/time.nim
Labels: track:maintenance

#1142 refactor(utils): split message digest calculation form index calculation
  waku/v2/utils/pagination.nim
Labels: track:maintenance

#1141 refactor(store): rename to sqlite store and introduce retention policies interface
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/sqlite_store.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/node/storage/message/sqlite_store/retention_policy.nim
  waku/v2/node/storage/message/sqlite_store/retention_policy_capacity.nim
  waku/v2/node/storage/message/sqlite_store/retention_policy_time.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/message/waku_message_store.nim
Labels: track:maintenance

#1119 feat(store): Allow messages to be marked as "don't store"
  tests/v2/test_waku_store.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/utils/protobuf.nim
Labels: track:production

#1133 docs(operator-outreach): nwaku on droplets
  docs/operators/droplet-quickstart.md
  docs/operators/quickstart.md
Labels: track:operator-outreach

#1150 fix(store): follow good practices in store insert and query metrics
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1163 refactor(store): don't cache the message count in sqlite message store
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1165 refactor(store): extend message store interface with store manipulation methods
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
Labels: track:production

#1164 refactor(store): invert retention policies dependency on message store interface
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  waku/v2/node/config.nim
  waku/v2/node/storage/message/message_retention_policy.nim
  waku/v2/node/storage/message/message_retention_policy_capacity.nim
  waku/v2/node/storage/message/message_retention_policy_time.nim
  waku/v2/node/storage/message/sqlite_store.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1161 fix: nodes in AddressBook are not necessarily connected
  waku/v2/node/wakunode2.nim
Labels: track:maintenance

#1166 chore: update existing Grafana dashboards
  metrics/waku-fleet-dashboard.json
  metrics/waku-single-node-dashboard.json
Labels: track:production

#1168 docs: add monitoring guide for prometheus and grafana
  docs/operators/how-to/monitor.md
Labels: track:production

#1167 refactor(store): protocol code refactoring and api reorganization
  examples/v2/chat2.nim
  tests/all_tests_v2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_store.nim
  waku/common/wakubridge.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/rpc.nim
Labels: track:production

#1158 feat(rln-relay): validate the merkle root in the RateLimitProof
  tests/v2/test_waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1162 fix: no need to start protocols twice
  waku/v2/node/wakunode2.nim
Labels: track:maintenance

#1169 feat(store): execute retention policies periodically (#1155)
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1172 refactor(wakunode): remove deprecated non-async methods
  examples/v2/chat2.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/jsonrpc/store_api.nim
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1175 chore(store): move constants to retention policies modules
  tests/v2/test_message_store_queue.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/storage/message/message_retention_policy_capacity.nim
  waku/v2/node/storage/message/message_retention_policy_time.nim
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/rpc_codec.nim
  waku/v2/utils/pagination.nim
Labels: track:maintenance

#1180 chore(ci): skip test workflow execution for docs changes
  .github/workflows/test.yml
Labels: infra

#1181 fix: fail to start switch with ext ip
  waku/v2/node/wakunode2.nim
Labels: track:maintenance

#1176 chore(rln-relay): specifies the address type for the eth-client-address config parameter
  examples/v2/config_chat2.nim
  waku/v2/node/config.nim
Labels: track:rln

#1178 fix(store): move insert criteria logic to waku store protocol module
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/utils/pagination.nim
Labels: track:production

#1177 feat(rln-relay): multiple acceptable roots
  tests/v2/test_waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1183 fix(store): rename store timestamp sqlite column
  tests/v2/test_message_store_sqlite_query.nim
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/node/storage/migration/migration_types.nim
  waku/v2/node/storage/migration/migrations_scripts/message/00006_renameColumn.up.sql
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1187 refactor(store): decouple message store queue from pagination index type
  tests/all_tests_v2.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_index.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_rpc_codec.nim
  waku/v2/node/jsonrpc/jsonrpc_types.nim
  waku/v2/node/jsonrpc/jsonrpc_utils.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/queue_store/index.nim
  waku/v2/node/storage/message/queue_store/queue_store.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/rpc_codec.nim
  waku/v2/utils/pagination.nim
Labels: track:maintenance

#1191 chore(store): collocate pagination and message store types
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_rpc_codec.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/jsonrpc/jsonrpc_types.nim
  waku/v2/node/jsonrpc/jsonrpc_utils.nim
  waku/v2/node/jsonrpc/store_api.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/storage/message/message_retention_policy.nim
  waku/v2/node/storage/message/message_retention_policy_capacity.nim
  waku/v2/node/storage/message/message_retention_policy_time.nim
  waku/v2/node/storage/message/queue_store/index.nim
  waku/v2/node/storage/message/queue_store/queue_store.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_store.nim
  waku/v2/protocol/waku_store/message_store.nim
  waku/v2/protocol/waku_store/pagination.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/rpc.nim
  waku/v2/protocol/waku_store/rpc_codec.nim
Labels: track:maintenance

#1185 feat(rln-relay): metrics
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_wakunode_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/rln_relay_contract.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_constants.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_metrics.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
  waku/v2/utils/time.nim
Labels: track:rln
