Repository waku-org/nwaku, pull requests merged in 2022-11, with the labels that each got.

#1318 fix(rln-relay): RangeDefect test
  tests/v2/test_waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_constants.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1296 feat(rln-relay): track last seen event
  tests/v2/test_waku_rln_relay_onchain.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1320 refactor(peer-exchange): move peer management to waku_node module
  apps/wakunode2/wakunode2.nim
  tests/v2/test_waku_peer_exchange.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_peer_exchange.nim
  waku/v2/protocol/waku_peer_exchange/client.nim
  waku/v2/protocol/waku_peer_exchange/protocol.nim
Labels: track:maintenance

#1319 feat(filter): split waku filter protocol into server and client
  apps/chat2/chat2.nim
  apps/wakunode2/wakunode2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_waku_filter.nim
  tests/v2/test_wakunode_filter.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/jsonrpc/filter_api.nim
  waku/v2/node/waku_metrics.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_filter.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_filter/protocol.nim
  waku/v2/protocol/waku_filter/protocol_metrics.nim
  waku/v2/protocol/waku_filter/rpc_codec.nim
Labels: track:maintenance

#1326 fix: replace TaintedString type deprecated in nim 1.5
  apps/chat2/config_chat2.nim
  apps/chat2bridge/config_chat2bridge.nim
  apps/wakubridge/config_bridge.nim
  apps/wakunode2/config.nim
  examples/v1/config_example.nim
  tools/wakucanary/wakucanary.nim
  waku/v1/node/config.nim
  waku/v2/node/discv5/waku_discv5.nim
  waku/v2/protocol/waku_swap/waku_swap_contracts.nim
Labels: track:maintenance

#1325 refactor(sqlite): move migrations logic to sqlite common module
  tests/all_tests_v2.nim
  tests/v2/test_migration_utils.nim
  tests/v2/test_sqlite_migrations.nim
  waku/common/sqlite.nim
  waku/common/sqlite/database.nim
  waku/common/sqlite/migrations.nim
Labels: track:maintenance

#1328 fix(wakunode2): fix message retention policy config validation regex
  apps/wakunode2/config.nim
Labels: track:maintenance

#1329 refactor(wakunode2): move configuration load logic to config module
  apps/wakunode2/config.nim
  apps/wakunode2/wakunode2.nim
  examples/v2/basic2.nim
Labels: track:maintenance

#1336 chore: randomize waku tcp ports in tests
  tests/v2/test_enr_utils.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_peer_exchange.nim
  tests/v2/test_utils_peers.nim
  tests/v2/test_waku_bridge.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_dnsdisc.nim
  tests/v2/test_waku_keepalive.nim
  tests/v2/test_waku_peer_exchange.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_relay.nim
  tests/v2/test_wakunode_rln_relay.nim
Labels: track:maintenance

#1334 chore: make log topics consistent with nim-chronicles style
  waku/v2/node/discv5/waku_discv5.nim
  waku/v2/node/dnsdisc/waku_dnsdisc.nim
  waku/v2/node/jsonrpc/admin_api.nim
  waku/v2/node/jsonrpc/debug_api.nim
  waku/v2/node/jsonrpc/filter_api.nim
  waku/v2/node/jsonrpc/private_api.nim
  waku/v2/node/jsonrpc/relay_api.nim
  waku/v2/node/jsonrpc/store_api.nim
  waku/v2/node/message_cache.nim
  waku/v2/node/peer_manager/peer_manager.nim
  waku/v2/node/rest/debug/debug_api.nim
  waku/v2/node/rest/relay/relay_api.nim
  waku/v2/node/rest/relay/topic_cache.nim
  waku/v2/node/rest/serdes.nim
  waku/v2/node/storage/message/message_retention_policy_capacity.nim
  waku/v2/node/storage/message/message_retention_policy_time.nim
  waku/v2/node/storage/message/queue_store/queue_store.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/waku_metrics.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_filter/protocol.nim
  waku/v2/protocol/waku_lightpush/client.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_noise/noise.nim
  waku/v2/protocol/waku_noise/noise_handshake_processing.nim
  waku/v2/protocol/waku_noise/noise_types.nim
  waku/v2/protocol/waku_noise/noise_utils.nim
  waku/v2/protocol/waku_peer_exchange/protocol.nim
  waku/v2/protocol/waku_relay.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_metrics.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_swap/waku_swap.nim
  waku/v2/protocol/waku_swap/waku_swap_contracts.nim
Labels: track:maintenance

#1330 chore(migrations): move migration scripts to project root
  migrations/message_store/00001_addMessageTable.up.sql
  migrations/message_store/00002_addSenderTimeStamp.up.sql
  migrations/message_store/00003_convertTimestampsToInt64.up.sql
  migrations/message_store/00004_extendPrimaryKey.up.sql
  migrations/message_store/00005_updateIndex.up.sql
  migrations/message_store/00006_renameColumn.up.sql
  migrations/message_store/00007_updatePrimaryKey.up.sql
  migrations/peer_store/00001_addPeerTable.up.sql
  waku/v2/node/storage/migration/migration_types.nim
Labels: track:production

#1337 feat(testlib): mark commented test cases as skipped
  tests/v2/testlib/testutils.nim
Labels: track:production

#1331 feat(wakunode2): support configuration via environment variables
  apps/wakunode2/config.nim
  apps/wakunode2/wakunode2.nim
  tests/all_tests_v2.nim
  tests/v2/test_confutils_envvar.nim
  tests/v2/test_envvar_serialization.nim
  waku/common/confutils/envvar/defs.nim
  waku/common/confutils/envvar/std/net.nim
  waku/common/envvar_serialization.nim
  waku/common/envvar_serialization/reader.nim
  waku/common/envvar_serialization/utils.nim
  waku/common/envvar_serialization/writer.nim
Labels: track:production

#1321 chore(rln-relay): remove all raises and replace with Result types
  apps/chat2/chat2.nim
  apps/wakunode2/wakunode2.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_wakunode_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln, track:maintenance

#1339 refactor(peer_manager): move peer_store under peer_manager module
  apps/wakunode2/wakunode2.nim
  apps/wakunode2/wakunode2_setup_rest.nim
  apps/wakunode2/wakunode2_setup_rpc.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_peer_storage.nim
  waku/v2/node/peer_manager/peer_manager.nim
  waku/v2/node/peer_manager/peer_store/migrations.nim
  waku/v2/node/peer_manager/peer_store/peer_storage.nim
  waku/v2/node/peer_manager/peer_store/waku_peer_storage.nim
Labels: track:production

#1340 chore: remove unused imports
  apps/chat2/chat2.nim
  apps/chat2bridge/chat2bridge.nim
  apps/wakunode2/wakunode2.nim
  tests/v1/test_rpc_waku.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_peer_exchange.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_peer_storage.nim
  tests/v2/test_rest_debug_api.nim
  tests/v2/test_rest_debug_api_serdes.nim
  tests/v2/test_rest_relay_api.nim
  tests/v2/test_waku_bridge.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_filter.nim
  tests/v2/test_waku_keepalive.nim
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_waku_noise_sessions.nim
  tests/v2/test_waku_peer_exchange.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  tests/v2/test_waku_store_rpc_codec.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_filter.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_rln_relay.nim
  tests/v2/test_wakunode_store.nim
  tests/whisper/test_shh_config.nim
  waku/v1/node/rpc/hexstrings.nim
  waku/v1/node/rpc/rpc_types.nim
  waku/v1/node/rpc/waku.nim
  waku/v1/node/wakunode1.nim
  waku/v2/node/jsonrpc/admin_api.nim
  waku/v2/node/rest/debug/debug_api.nim
  waku/v2/node/rest/serdes.nim
  waku/v2/node/waku_metrics.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_noise/noise.nim
  waku/v2/protocol/waku_noise/noise_handshake_processing.nim
  waku/v2/protocol/waku_noise/noise_types.nim
  waku/v2/protocol/waku_noise/noise_utils.nim
  waku/v2/protocol/waku_peer_exchange/protocol.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_store/rpc.nim
Labels: track:maintenance

#1342 refactor(message_store): move message_store to node module
  apps/wakunode2/wakunode2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_index.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  tests/v2/test_waku_store_resume.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/message_store/message_retention_policy.nim
  waku/v2/node/message_store/message_retention_policy_capacity.nim
  waku/v2/node/message_store/message_retention_policy_time.nim
  waku/v2/node/message_store/queue_store/index.nim
  waku/v2/node/message_store/queue_store/queue_store.nim
  waku/v2/node/message_store/sqlite_store.nim
  waku/v2/node/message_store/sqlite_store/migrations.nim
  waku/v2/node/message_store/sqlite_store/queries.nim
  waku/v2/node/message_store/sqlite_store/sqlite_store.nim
  waku/v2/node/message_store/waku_store_queue.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/storage/migration.nim
  waku/v2/node/storage/migration/migration_types.nim
  waku/v2/node/storage/migration/migration_utils.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1344 chore: build rln dependecies only when building v2
  Makefile
  apps/chat2/nim.cfg
  apps/chat2bridge/nim.cfg
  apps/wakubridge/nim.cfg
  apps/wakunode2/nim.cfg
  examples/v1/nim.cfg
  examples/v2/nim.cfg
  tests/nim.cfg
  tools/wakucanary/nim.cfg
Labels: infra

#1346 chore: rename protocols rpc_codec procs from init to decode
  apps/chat2/chat2.nim
  apps/chat2bridge/chat2bridge.nim
  apps/wakubridge/wakubridge.nim
  examples/v2/basic2.nim
  examples/v2/subscriber.nim
  tests/v2/test_waku_bridge.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_noise.nim
  tests/v2/test_waku_noise_sessions.nim
  tests/v2/test_waku_payload.nim
  tests/v2/test_waku_peer_exchange.nim
  tests/v2/test_waku_store_rpc_codec.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_relay.nim
  tests/v2/test_wakunode_rln_relay.nim
  waku/v2/node/jsonrpc/relay_api.nim
  waku/v2/node/rest/relay/topic_cache.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_filter/protocol.nim
  waku/v2/protocol/waku_filter/rpc_codec.nim
  waku/v2/protocol/waku_lightpush/client.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_lightpush/rpc_codec.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_peer_exchange/protocol.nim
  waku/v2/protocol/waku_peer_exchange/rpc_codec.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/rpc_codec.nim
Labels: track:maintenance

#1351 fix(rln-relay): remove dependency on applications' configuration
  apps/chat2/chat2.nim
  apps/wakunode2/wakunode2.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1348 refactor(queue_store): rename queue_store module and simplify api
  apps/wakunode2/wakunode2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/message_store/queue_store.nim
  waku/v2/node/message_store/queue_store/queue_store.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_store/message_store.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1355 docs: extend docs with the different node configuration mechanisms
  docs/operators/how-to/configure.md
Labels: track:production

#1352 refactor: unify pubsub topic type and default value
  apps/chat2/chat2.nim
  apps/chat2bridge/chat2bridge.nim
  apps/wakubridge/wakubridge.nim
  tests/v2/test_peer_exchange.nim
  tests/v2/test_rest_relay_api.nim
  tests/v2/test_waku_filter.nim
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_store.nim
  tests/v2/testlib/common.nim
  tools/simulation/quicksim2.nim
  waku/v2/node/jsonrpc/filter_api.nim
  waku/v2/node/message_store/queue_store/index.nim
  waku/v2/node/message_store/queue_store/queue_store.nim
  waku/v2/node/message_store/sqlite_store/queries.nim
  waku/v2/node/message_store/sqlite_store/sqlite_store.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_filter/protocol.nim
  waku/v2/protocol/waku_filter/rpc_codec.nim
  waku/v2/protocol/waku_lightpush/client.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_lightpush/rpc_codec.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_relay.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/message_store.nim
  waku/v2/protocol/waku_store/pagination.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1350 refactor(store): decouple waku store public api types from rpc types
  apps/chat2/chat2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  tests/v2/test_waku_store_rpc_codec.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_store.nim
  tools/scripts/rpc_query.nim
  tools/simulation/quicksim2.nim
  waku/v2/node/jsonrpc/jsonrpc_callsigs.nim
  waku/v2/node/jsonrpc/jsonrpc_types.nim
  waku/v2/node/jsonrpc/jsonrpc_utils.nim
  waku/v2/node/jsonrpc/store_api.nim
  waku/v2/node/message_store/queue_store/index.nim
  waku/v2/node/message_store/queue_store/queue_store.nim
  waku/v2/node/message_store/sqlite_store/sqlite_store.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_store.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/common.nim
  waku/v2/protocol/waku_store/message_store.nim
  waku/v2/protocol/waku_store/pagination.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/protocol_metrics.nim
  waku/v2/protocol/waku_store/rpc.nim
  waku/v2/protocol/waku_store/rpc_codec.nim
Labels: track:production

#1359 docs: extend waku store config tutorial of the operator docs
  docs/operators/how-to/configure-store-v0.12.0.md
  docs/operators/how-to/configure-store.md
Labels: documentation, track:production

#1373 fix(rln-relay): feature guard
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_message.nim
Labels: track:rln, track:maintenance

#1393 fix(store): waku store rpc codec support optional fields
  tests/v2/test_waku_store_rpc_codec.nim
  waku/common/protobuf.nim
  waku/v2/node/jsonrpc/jsonrpc_utils.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/rpc.nim
  waku/v2/protocol/waku_store/rpc_codec.nim
Labels: track:production

#1397 refactor(relay): collocate relay protocol initialization logic
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_relay.nim
Labels: track:production

#1396 fix(filter): waku filter rpc codec support optional fields
  waku/common/protobuf.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_filter/protocol.nim
  waku/v2/protocol/waku_filter/rpc.nim
  waku/v2/protocol/waku_filter/rpc_codec.nim
Labels: track:production

#1395 fix(lightpush): waku lightpush rpc codec support optional fields
  waku/v2/protocol/waku_lightpush/client.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_lightpush/rpc.nim
  waku/v2/protocol/waku_lightpush/rpc_codec.nim
Labels: track:production

#1403 chore: add editorconfig file
  .editorconfig
Labels: track:maintenance

#1405 feat(store): add support for history query handler
  tests/v2/test_waku_store.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1386 chore(rln-relay): barrel imports
  apps/chat2/chat2.nim
  apps/wakunode2/wakunode2.nim
  docs/tutorial/onchain-rln-relay-chat2.md
  docs/tutorial/rln-chat2-live-testnet.md
  docs/tutorial/rln-chat2-local-test.md
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_wakunode_rln_relay.nim
  waku/v2/node/waku_metrics.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/constants.nim
  waku/v2/protocol/waku_rln_relay/protocol_metrics.nim
  waku/v2/protocol/waku_rln_relay/protocol_types.nim
  waku/v2/protocol/waku_rln_relay/rln.nim
  waku/v2/protocol/waku_rln_relay/utils.nim
Labels: track:rln, track:production

#1399 refactor(rln): decouple rln types from waku message type
  apps/chat2/chat2.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_wakunode_rln_relay.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_rln_relay/utils.nim
Labels: track:production

#1409 feat(archive): add waku archive implementation
  apps/wakubridge/wakubridge.nim
  apps/wakunode2/config.nim
  apps/wakunode2/wakunode2.nim
  tests/all_tests_v2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_index.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  tests/v2/test_waku_store_resume.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/jsonrpc/jsonrpc_utils.nim
  waku/v2/node/message_store/message_retention_policy.nim
  waku/v2/node/message_store/message_retention_policy_capacity.nim
  waku/v2/node/message_store/message_retention_policy_time.nim
  waku/v2/node/message_store/queue_store.nim
  waku/v2/node/message_store/queue_store/index.nim
  waku/v2/node/message_store/queue_store/queue_store.nim
  waku/v2/node/message_store/sqlite_store.nim
  waku/v2/node/message_store/sqlite_store/migrations.nim
  waku/v2/node/message_store/sqlite_store/queries.nim
  waku/v2/node/message_store/sqlite_store/sqlite_store.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_archive/archive.nim
  waku/v2/protocol/waku_archive/driver/sqlite_driver/migrations.nim
  waku/v2/protocol/waku_store.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/common.nim
  waku/v2/protocol/waku_store/message_store.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/rpc.nim
Labels: track:production

#1411 test(archive): randomize archive driver query test suites' fixtures
  tests/v2/testlib/common.nim
  tests/v2/waku_archive/test_driver_queue_query.nim
  tests/v2/waku_archive/test_driver_sqlite_query.nim
Labels: track:production

#1415 fix(archive): patch the sqlite driver to solve results inconsistencies
  waku/common/sqlite/database.nim
Labels: track:maintenance

#1417 chore(store): remove obsolete metrics and error labels
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/protocol_metrics.nim
Labels: track:maintenance

#1437 chore(build): simplify project makefile and update dockerfile
  Dockerfile
  Makefile
  waku/v2/protocol/waku_rln_relay/rln.nim
Labels: track:maintenance
