Repository waku-org/nwaku, pull requests merged in 2022-08, with the labels that each got.

#1055 refactor(waku-store): reorganise pagination test cases
  tests/all_tests_v2.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_utils_pagination.nim
  tests/v2/test_waku_payload.nim
Labels: track:nwaku-maintenance

#1044 chore(Rln-relay): Tutorial on how to run rln-chat2 in on-chain mode
  docs/tutorial/imgs/rln-relay-chat2-overview.png
  docs/tutorial/onchain-rln-relay-chat2.md
  docs/tutorial/pre-requisites-of-running-on-chain-spam-protected-chat2.md
Labels: track:rln

#1037 Persisting rln credentials
  .gitignore
  tests/v2/test_waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1067 refactor(waku-lightpush): waku lightpush protocol code reorganization
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_wakunode.nim
  waku/v2/node/wakunode2.nim
  waku/v2/node/wakunode2_types.nim
  waku/v2/protocol/waku_lightpush.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_lightpush/rpc.nim
  waku/v2/protocol/waku_lightpush/rpc_codec.nim
  waku/v2/protocol/waku_lightpush/waku_lightpush.nim
  waku/v2/protocol/waku_lightpush/waku_lightpush_types.nim
Labels: track:nwaku-maintenance

#1072 refactor(waku-lightpush): remove wakunode2 waku_lightpush exports
  examples/v2/chat2.nim
  waku/v2/node/wakunode2.nim
Labels: track:nwaku-maintenance

#1070 refactor(waku-store): inherit from message_store in store_queue
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:nwaku-maintenance

#1073 fix(waku-store): integrate the predicate into the WHERE clause instead of calling it on each result line (#1026)
  tests/all_tests_v2.nim
  tests/v2/test_message_store.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_utils_pagination.nim
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_waku_store_rpc_codec.nim
  tests/v2/test_wakunode.nim
  waku/v2/node/storage/message/message_store.nim
  waku/v2/node/storage/message/waku_message_store.nim
  waku/v2/node/storage/message/waku_message_store_queries.nim
  waku/v2/node/storage/message/waku_store_queue.nim
  waku/v2/node/storage/sqlite.nim
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:nwaku-maintenance

#1078 refactor(waku-store): deprecate waku store callback methods
  tests/v2/test_waku_store.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:nwaku-maintenance

#1068 chore(RLN-Relay): onchain rln-relay chat2 testnet editorial feadbacks
  docs/tutorial/imgs/infura-dashboard-mainnet.png
  docs/tutorial/onchain-rln-relay-chat2.md
  docs/tutorial/pre-requisites-of-running-on-chain-spam-protected-chat2.md
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1079 refactor(waku-store): remove wakunode2 waku_store exports
  tests/v2/test_peer_manager.nim
  waku/v2/node/jsonrpc/admin_api.nim
  waku/v2/node/wakunode2.nim
Labels: track:nwaku-maintenance

#1080 feat(Rln-Relay): Consolidates the input paths of rln credential, chat2 reads rln credential from file only
  docs/tutorial/onchain-rln-relay-chat2.md
  examples/v2/config_chat2.nim
  waku/v2/node/config.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1082 feat(Rln relay): Improves rln-chat2 interface, displays links to the registration tx, warns about spam messages
  examples/v2/chat2.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1084 refactor(waku-filter): waku filter protocol code reorganisation
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_waku_bridge.nim
  tests/v2/test_waku_filter.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_wakunode.nim
  waku/v2/node/quicksim2.nim
  waku/v2/node/scripts/rpc_info.nim
  waku/v2/node/scripts/rpc_publish.nim
  waku/v2/node/scripts/rpc_query.nim
  waku/v2/node/scripts/rpc_subscribe.nim
  waku/v2/node/scripts/rpc_subscribe_filter.nim
  waku/v2/node/wakunode2.nim
  waku/v2/node/wakunode2_types.nim
  waku/v2/protocol/waku_filter.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_filter/protocol.nim
  waku/v2/protocol/waku_filter/rpc.nim
  waku/v2/protocol/waku_filter/rpc_codec.nim
  waku/v2/protocol/waku_filter/waku_filter.nim
  waku/v2/protocol/waku_filter/waku_filter_types.nim
Labels: track:maintenance

#1092 refactor(waku-filter): remove wakunode2 waku_filter exports
  examples/v2/chat2.nim
  tests/v2/test_peer_manager.nim
  waku/v2/node/jsonrpc/admin_api.nim
  waku/v2/node/jsonrpc/filter_api.nim
  waku/v2/node/wakunode2.nim
Labels: track:maintenance

#1095 fix(rest): encode waku message payload in base64
  tests/v2/test_rest_relay_api.nim
  tests/v2/test_rest_relay_api_serdes.nim
  waku/v2/node/rest/base64.nim
  waku/v2/node/rest/relay/api_types.nim
  waku/v2/node/rest/relay/relay_api.nim
  waku/v2/node/rest/relay/relay_api.yaml
  waku/v2/node/rest/serdes.nim
Labels: track:maintenance

#1097 feat(message-cache): make the topic cache generic
  tests/all_tests_v2.nim
  tests/v2/test_message_cache.nim
  waku/v2/node/config.nim
  waku/v2/node/message_cache.nim
  waku/v2/node/rest/relay/topic_cache.nim
  waku/v2/node/wakunode2_setup_rest.nim
Labels: track:production

#1093 fix|feat(rln-relay|rln-chat2): Handling on-chain transactions errors and informing chat2 users
  examples/v2/chat2.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1094 Periodic logging for additional metrics
  waku/v2/node/config.nim
  waku/v2/node/wakunode2_setup_metrics.nim
Labels: track:production

#1096 feat(rest): add waku filter openapi rest api specification file
  waku/v2/node/rest/filter/openapi.yaml
Labels: track:production

#1100 chore(lightpush): Fix typo in annotation
  waku/v2/protocol/waku_lightpush/rpc.nim
Labels: track:maintenance

#1014 Fixed handling of bindParam(uint32) in sqlite.nim
  waku/v2/node/storage/sqlite.nim
Labels: track:maintenance
