Repository waku-org/nwaku, pull requests merged in 2022-10, with the labels that each got.

#1211 refactor(store): simplify store queue query implementation
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_pagination.nim
  waku/v2/node/storage/message/queue_store/queue_store.nim
Labels: track:production

#1212 fix(store): update sqlite db table primary key and decouple queries module from pagination types
  tests/v2/test_message_store_sqlite.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/migration/migration_types.nim
  waku/v2/node/storage/migration/migrations_scripts/message/00007_updatePrimaryKey.up.sql
Labels: track:production

#1215 fix(store): Move page info logic to waku store protocol
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_message_store_queue.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_waku_store.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/storage/message/queue_store/queue_store.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/protocol/waku_store/message_store.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:production

#1216 [WIP] ci: use Nix shell to provide build dependencies
  ci/Jenkinsfile.prs
  shell.nix
Labels: infra

#1204 chore(rln-relay): namespaced flags
  docs/tutorial/onchain-rln-relay-chat2.md
  examples/v2/config_chat2.nim
  waku/v2/node/config.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln, track:maintenance

#1219 feat(rln-relay): adds rln identifier to the RateLimitProof
  waku/v2/node/wakunode2.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
Labels: track:rln

#1190 chore(Makefile): Make zerokit the default RLN implementation
  Makefile
  shell.nix
Labels: infra

#1225 chore(store): improve database migrations logging
  tests/v2/test_message_store_sqlite.nim
  waku/v2/node/storage/migration.nim
  waku/v2/node/storage/migration/migration_types.nim
  waku/v2/node/storage/migration/migration_utils.nim
  waku/v2/node/storage/sqlite.nim
  waku/v2/node/wakunode2_setup_sql_migrations.nim
Labels: track:production

#1230 ci: install 1.64 rust in Docker image
  Dockerfile
Labels: infra

#1246 chore(rln-relay): disable merkle root validation
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1243 chore(rln-relay): additional logging
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1253 test(rln-relay): setup heartbeat ws subscription and log when connection drops
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1258 chore(rln-relay): make account address optional
  docs/tutorial/onchain-rln-relay-chat2.md
  examples/v2/chat2.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:rln

#1260 ci: add username and email to build notifications
  ci/Jenkinsfile.release
Labels: infra

#1262 feat(rln-relay): periodically log metrics
  waku/v2/node/wakunode2_setup_metrics.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_metrics.nim
  waku/v2/utils/collector.nim
Labels: track:rln

#1274 refactor(node): split wakunode into waku_node and wakunode2
  apps/chat2/chat2.nim
  apps/chat2bridge/chat2bridge.nim
  apps/wakubridge/wakubridge.nim
  examples/v2/basic2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_peer_exchange.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_rest_debug_api.nim
  tests/v2/test_rest_relay_api.nim
  tests/v2/test_waku_bridge.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_dnsdisc.nim
  tests/v2/test_waku_keepalive.nim
  tests/v2/test_waku_peer_exchange.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_filter.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_relay.nim
  tests/v2/test_wakunode_rln_relay.nim
  tests/v2/test_wakunode_store.nim
  tools/scripts/rpc_info.nim
  tools/scripts/rpc_publish.nim
  tools/scripts/rpc_query.nim
  tools/scripts/rpc_subscribe.nim
  tools/scripts/rpc_subscribe_filter.nim
  tools/simulation/quicksim2.nim
  tools/wakucanary/wakucanary.nim
  waku/v2/node/jsonrpc/admin_api.nim
  waku/v2/node/jsonrpc/debug_api.nim
  waku/v2/node/jsonrpc/filter_api.nim
  waku/v2/node/jsonrpc/private_api.nim
  waku/v2/node/jsonrpc/relay_api.nim
  waku/v2/node/jsonrpc/store_api.nim
  waku/v2/node/rest/debug/api_types.nim
  waku/v2/node/rest/debug/debug_api.nim
  waku/v2/node/rest/relay/relay_api.nim
  waku/v2/node/storage/message/dual_message_store.nim
  waku/v2/node/waku_node.nim
  waku/v2/node/wakunode2.nim
  waku/v2/node/wakunode2_setup_metrics.nim
  waku/v2/node/wakunode2_setup_rest.nim
  waku/v2/node/wakunode2_setup_rpc.nim
  waku/v2/node/wakunode2_types.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
  waku/waku.nim
Labels: track:maintenance

#1277 chore(wakunode2): move wakunode2 to apps directory
  apps/wakunode2/config.nim
  apps/wakunode2/nim.cfg
  apps/wakunode2/wakunode2.nim
  apps/wakunode2/wakunode2_setup_metrics.nim
  apps/wakunode2/wakunode2_setup_rest.nim
  apps/wakunode2/wakunode2_setup_rpc.nim
  apps/wakunode2/wakunode2_setup_sql_migrations.nim
  examples/v2/basic2.nim
  waku.nimble
  waku/v2/node/discv5/waku_discv5.nim
  waku/v2/node/wakunode2_setup.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_utils.nim
Labels: track:maintenance

#1275 feat(rln-relay): add metrics dashboard
  metrics/waku-rln-relay-fleet-dashboard.json
  metrics/waku-rln-relay-single-node-dashboard.json
Labels: infra, track:rln

#1263 fix: store cursors should be exclusive and match a DB item
  tests/v2/test_waku_store.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1281 chore(store): disable temporarily the store resume flaky test case
  tests/all_tests_v2.nim
Labels: track:maintenance

#1229 feat(store): add waku store client module
  apps/wakunode2/wakunode2_setup_metrics.nim
  tests/all_tests_v2.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/protocol_metrics.nim
Labels: track:production

#1279 feat(chat2): metrics server + metrics logging
  apps/chat2/chat2.nim
  apps/chat2/config_chat2.nim
  apps/wakunode2/wakunode2.nim
  waku/v2/node/waku_metrics.nim
  waku/v2/protocol/waku_rln_relay/waku_rln_relay_metrics.nim
  waku/v2/utils/collector.nim
Labels: track:rln

#1287 chore: extract test procedures and constants into a common module
  tests/v2/test_message_cache.nim
  tests/v2/test_message_store_queue_index.nim
  tests/v2/test_message_store_queue_pagination.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_rest_relay_api.nim
  tests/v2/test_waku_filter.nim
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  tests/v2/test_waku_store_resume.nim
  tests/v2/test_waku_store_rpc_codec.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_relay.nim
  tests/v2/test_wakunode_store.nim
  tests/v2/testlib/common.nim
  tests/v2/testlib/switch.nim
Labels: track:maintenance

#1295 feat(lightpush): add waku lightpush protocol client
  tests/all_tests_v2.nim
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/testlib/common.nim
  waku/v2/node/waku_metrics.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_lightpush/client.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_lightpush/protocol_metrics.nim
  waku/v2/protocol/waku_lightpush/rpc_codec.nim
  waku/v2/protocol/waku_store/client.nim
Labels: track:production

#1299 ci(jenkins): use MAKEFLAGS and NIMFLAGS pipeline params in build and test stages
  ci/Jenkinsfile.prs
Labels: infra

#1293 feat(store): simplify wakunode2 configuration options
  apps/wakunode2/config.nim
  shell.nix
Labels: track:production

#1303 chore(node): waku node code reorganization
  apps/chat2/chat2.nim
  apps/wakubridge/wakubridge.nim
  examples/v2/basic2.nim
  waku/v2/node/waku_node.nim
Labels: track:maintenance

#1300 feat(wakunode2): simplify wakunode2 config and decouple peer persistence
  apps/wakunode2/config.nim
  apps/wakunode2/wakunode2.nim
  apps/wakunode2/wakunode2_setup_sql_migrations.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_peer_storage.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/storage/migration/migration_types.nim
  waku/v2/node/storage/sqlite.nim
Labels: track:production

#1280 chore(rln-relay): removes the Goerli account address config option from the onchain-rln-relay tutorial
  docs/tutorial/onchain-rln-relay-chat2.md
Labels: track:rln

#1315 feat(testlib): add enable/disable test debug utils
  tests/v2/testlib/testutils.nim
Labels: track:maintenance

#1316 chore: remove legacy unused test suite
  tests/all_tests_v2.nim
  tests/v2/test_waku.nim
Labels: track:maintenance

#1309 refactor(node): use store client in waku_node
  apps/chat2/chat2.nim
  apps/wakunode2/wakunode2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_wakunode_store.nim
  waku/v2/node/jsonrpc/store_api.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_store/protocol_metrics.nim
Labels: track:maintenance

#1317 chore(common): move sqlite module to common module
  apps/wakunode2/wakunode2.nim
  tests/v2/test_message_store_sqlite.nim
  tests/v2/test_message_store_sqlite_query.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_peer_storage.nim
  tests/v2/test_waku_store.nim
  tests/v2/test_waku_store_client.nim
  tests/v2/test_waku_store_resume.nim
  tests/v2/test_wakunode_store.nim
  waku/common/sqlite.nim
  waku/v2/node/storage/message/sqlite_store/queries.nim
  waku/v2/node/storage/message/sqlite_store/sqlite_store.nim
  waku/v2/node/storage/migration.nim
  waku/v2/node/storage/peer/waku_peer_storage.nim
Labels: track:maintenance

#1311 docs(operator-trial): add rln instructions
  docs/operators/droplet-quickstart.md
  docs/operators/how-to/configure.md
  docs/operators/how-to/run-with-rln.md
Labels: track:rln, track:operator-outreach
