Repository waku-org/nwaku, pull requests merged in 2023-06, with the labels that each got.

#1777 feat(rln-relay): pass in index to keystore credentials
  apps/chat2/chat2.nim
  apps/chat2/config_chat2.nim
  apps/wakunode2/app.nim
  apps/wakunode2/config.nim
  docs/tutorial/onchain-rln-relay-chat2.md
  tests/v2/waku_rln_relay/test_waku_rln_relay.nim
  tests/v2/waku_rln_relay/test_wakunode_rln_relay.nim
  waku/v2/waku_rln_relay/group_manager/on_chain/group_manager.nim
  waku/v2/waku_rln_relay/group_manager/static/group_manager.nim
  waku/v2/waku_rln_relay/rln_relay.nim
Labels: track:rlnp2p

#1781 chore(rln-relay): update tree_config
  waku/v2/waku_rln_relay/constants.nim
Labels: track:rlnp2p

#1790 feat(rln-relay): integrate get_leaf ffi api
  tests/v2/waku_rln_relay/test_waku_rln_relay.nim
  waku/v2/waku_rln_relay/constants.nim
  waku/v2/waku_rln_relay/rln/rln_interface.nim
  waku/v2/waku_rln_relay/rln/wrappers.nim
Labels: track:rlnp2p

#1798 fix(rln-relay): flaky static group manager test
  tests/v2/waku_rln_relay/test_rln_group_manager_static.nim
Labels: track:maintenance, track:rlnp2p

#1825 fix: sanity-check the docker image start
  ci/Jenkinsfile.release
Labels: infra
