Repository waku-org/nwaku, pull requests merged in 2023-10, with the labels that each got.

#2099 chore: Revert lightpush error handling to allow zero peer publish again succeed
  tests/wakunode_rest/test_rest_lightpush.nim
  waku/node/waku_node.nim
Labels: bug

#2094 feat: /admin rest api endpoint
  apps/wakunode2/app.nim
  tests/all_tests_waku.nim
  tests/wakunode_rest/test_all.nim
  tests/wakunode_rest/test_rest_admin.nim
  waku/waku_api/jsonrpc/admin/handlers.nim
  waku/waku_api/rest/admin/client.nim
  waku/waku_api/rest/admin/handlers.nim
  waku/waku_api/rest/admin/openapi.yaml
  waku/waku_api/rest/admin/types.nim
  waku/waku_core.nim
  waku/waku_core/multiaddrstr.nim
Labels: E:REST API service node

#2142 feat: messageHash attribute added in SQLite + testcase
  tests/waku_archive/test_driver_postgres.nim
  tests/waku_archive/test_driver_sqlite.nim
  tests/waku_archive/test_driver_sqlite_query.nim
  tests/waku_archive/test_retention_policy.nim
  waku/waku_archive/archive.nim
  waku/waku_archive/driver.nim
  waku/waku_archive/driver/postgres_driver/postgres_driver.nim
  waku/waku_archive/driver/queue_driver/queue_driver.nim
  waku/waku_archive/driver/sqlite_driver/queries.nim
  waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim
Labels: release-notes

#2141 feat: adding ext-multiaddr-only CLI flag
  apps/wakunode2/external_config.nim
  apps/wakunode2/internal_config.nim
  tests/test_waku_netconfig.nim
  waku/node/config.nim
Labels: release-notes

#2109 feat: API discovery handler
  apps/wakunode2/app.nim
  tests/wakunode_rest/test_rest_store.nim
  waku/waku_api/cache_handlers.nim
  waku/waku_api/handlers.nim
  waku/waku_api/jsonrpc/relay/handlers.nim
  waku/waku_api/rest/filter/handlers.nim
  waku/waku_api/rest/lightpush/handlers.nim
  waku/waku_api/rest/relay/handlers.nim
  waku/waku_api/rest/store/handlers.nim
Labels: E:1.4: Sharded peer management and discovery

#2149 feat: metadata protocol shard subscription
  tests/test_waku_metadata.nim
  waku/node/waku_node.nim
  waku/waku_metadata/protocol.nim
Labels: E:1.4: Sharded peer management and discovery

#2174 fix(ci): fix Docker tag for latest and release jobs
  ci/Jenkinsfile.release
Labels: infra
