Repository waku-org/nwaku, pull requests merged in 2023-02, with the labels that each got.

#1532 chore(v1): fix deprecation warnings
  waku/v1/node/rpc/waku.nim
  waku/whisper/whisper_types.nim
Labels: track:maintenance

#1533 chore(peer_manager): added peer_manager barrel module
  apps/chat2/chat2.nim
  apps/wakubridge/wakubridge.nim
  apps/wakunode2/wakunode2.nim
  examples/v2/publisher.nim
  examples/v2/subscriber.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_waku_dnsdisc.nim
  tests/v2/test_waku_filter.nim
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_waku_peer_exchange.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_filter.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_relay.nim
  tests/v2/waku_archive/test_waku_archive.nim
  tests/v2/waku_store/test_resume.nim
  tests/v2/waku_store/test_waku_store.nim
  tests/v2/waku_store/test_wakunode_store.nim
  tools/networkmonitor/networkmonitor.nim
  tools/wakucanary/wakucanary.nim
  waku/v2/node/jsonrpc/admin_api.nim
  waku/v2/node/jsonrpc/store_api.nim
  waku/v2/node/peer_manager.nim
  waku/v2/node/waku_metrics.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_filter/protocol.nim
  waku/v2/protocol/waku_lightpush/client.nim
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_peer_exchange/protocol.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/protocol.nim
  waku/v2/protocol/waku_swap/waku_swap.nim
  waku/v2/protocol/waku_swap/waku_swap_types.nim
Labels: track:maintenance

#1531 chore: remove unused test fixture file
  tests/v2/00002_test.up.sql
Labels: track:maintenance

#1534 chore(discv5): waku discv5 module code cleanup
  waku/v2/node/discv5/waku_discv5.nim
Labels: track:maintenance

#1536 refactor(utils): moved noise/compat payload encryption code to utils
  apps/chat2/chat2.nim
  tests/all_tests_v2.nim
  tests/v2/test_jsonrpc_waku.nim
  tests/v2/test_utils_compat.nim
  tests/v2/test_waku_bridge.nim
  tests/v2/test_waku_noise.nim
  tests/v2/test_waku_noise_sessions.nim
  tools/wakucanary/wakucanary.nim
  waku/v2/node/jsonrpc/jsonrpc_utils.nim
  waku/v2/node/jsonrpc/private_api.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/utils/compat.nim
  waku/v2/utils/noise.nim
Labels: track:maintenance

#1512 feat(discv5): advertise custom multiaddresses
  apps/wakunode2/wakunode2.nim
  examples/v2/publisher.nim
  examples/v2/subscriber.nim
  tests/v2/test_enr_utils.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_peer_exchange.nim
  waku/v2/node/discv5/waku_discv5.nim
  waku/v2/node/waku_node.nim
  waku/v2/utils/peers.nim
  waku/v2/utils/wakuenr.nim
Labels: track:maintenance

#1535 chore(tests): moved common test suites to its own folder
  tests/all_tests_common.nim
  tests/all_tests_v2.nim
  tests/common/test_confutils_envvar.nim
  tests/common/test_envvar_serialization.nim
  tests/common/test_sqlite_migrations.nim
Labels: track:maintenance

#1538 refactor(relay): improve wakuy relay api
  tests/v2/test_wakunode_relay.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_relay.nim
Labels: track:production

#1541 refactor(message): split waku message module into rpc and codec
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_message/codec.nim
  waku/v2/protocol/waku_message/message.nim
Labels: track:maintenance

#1544 refactor(wakubridge): split message compatibility from wakubridge
  apps/wakubridge/message_compat.nim
  apps/wakubridge/wakubridge.nim
  tests/all_tests_v2.nim
  tests/all_tests_wakubridge.nim
  tests/v2/test_namespacing_utils.nim
  tests/wakubridge/test_message_compat.nim
  tests/wakubridge/test_wakubridge.nim
Labels: track:maintenance

#1547 refactor(relay): improve waku_relay apis and add tests
  tests/all_tests_v2.nim
  tests/v2/test_rest_relay_api.nim
  tests/v2/testlib/switch.nim
  tests/v2/waku_relay/resources/test_cert.pem
  tests/v2/waku_relay/resources/test_key.pem
  tests/v2/waku_relay/test_waku_relay.nim
  tests/v2/waku_relay/test_wakunode_relay.nim
  waku/v2/node/rest/relay/api_types.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_relay.nim
  waku/v2/protocol/waku_rln_relay/utils.nim
Labels: track:production

#1548 fix(node): remove subscription to waku default network topic (#1545)
  tests/v2/test_peer_exchange.nim
  tests/v2/test_rest_relay_api.nim
  tests/v2/test_wakunode_rln_relay.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim
  waku/v2/node/waku_node.nim
Labels: track:production

#1551 feat(testlib): added global tests rng and waku2 sub-module
  tests/test_helpers.nim
  tests/v2/test_enr_utils.nim
  tests/v2/test_message_cache.nim
  tests/v2/test_peer_exchange.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_peer_storage.nim
  tests/v2/test_peer_store_extended.nim
  tests/v2/test_rest_debug_api.nim
  tests/v2/test_rest_relay_api.nim
  tests/v2/test_rest_relay_api_serdes.nim
  tests/v2/test_rln_group_manager_onchain.nim
  tests/v2/test_utils_compat.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_dnsdisc.nim
  tests/v2/test_waku_filter.nim
  tests/v2/test_waku_keepalive.nim
  tests/v2/test_waku_keystore.nim
  tests/v2/test_waku_keystore_keyfile.nim
  tests/v2/test_waku_lightpush.nim
  tests/v2/test_waku_noise.nim
  tests/v2/test_waku_noise_sessions.nim
  tests/v2/test_waku_peer_exchange.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_waku_swap.nim
  tests/v2/test_waku_swap_contracts.nim
  tests/v2/test_waku_switch.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_filter.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_rln_relay.nim
  tests/v2/testlib/common.nim
  tests/v2/testlib/switch.nim
  tests/v2/testlib/waku2.nim
  tests/v2/utils.nim
  tests/v2/waku_archive/test_driver_queue_index.nim
  tests/v2/waku_archive/test_driver_queue_pagination.nim
  tests/v2/waku_archive/test_driver_queue_query.nim
  tests/v2/waku_archive/test_driver_sqlite.nim
  tests/v2/waku_archive/test_driver_sqlite_query.nim
  tests/v2/waku_archive/test_retention_policy.nim
  tests/v2/waku_archive/test_waku_archive.nim
  tests/v2/waku_relay/test_waku_relay.nim
  tests/v2/waku_relay/test_wakunode_relay.nim
  tests/v2/waku_store/test_resume.nim
  tests/v2/waku_store/test_rpc_codec.nim
  tests/v2/waku_store/test_waku_store.nim
  tests/v2/waku_store/test_wakunode_store.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_admin.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_debug.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_filter.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim
Labels: track:maintenance

#1552 fix(tests): do not specify port number
  tests/v2/test_peer_exchange.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_waku_keepalive.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_wakunode_filter.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/test_wakunode_rln_relay.nim
  tests/v2/waku_relay/test_wakunode_relay.nim
  tests/v2/waku_store/test_resume.nim
  tests/v2/waku_store/test_wakunode_store.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_debug.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_filter.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim
Labels: track:production

#1553 fix: remove unused imports
  apps/wakubridge/wakubridge.nim
  apps/wakunode2/wakunode2.nim
  apps/wakunode2/wakunode2_setup_rpc.nim
  tests/v2/test_waku_keepalive.nim
  tests/v2/waku_relay/test_waku_relay.nim
  tests/v2/waku_relay/test_wakunode_relay.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_debug.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_filter.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim
  waku/v2/node/jsonrpc/filter/handlers.nim
  waku/v2/node/jsonrpc/store/handlers.nim
  waku/v2/node/peer_manager/peer_manager.nim
  waku/v2/protocol/waku_peer_exchange/protocol.nim
  waku/v2/protocol/waku_store/client.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1555 fix(jsonrpc): encode waku messages payload in base64 (#1139)
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim
  waku/common/base64.nim
  waku/common/hexstrings.nim
  waku/v2/node/jsonrpc/hexstrings.nim
  waku/v2/node/jsonrpc/marshalling.nim
  waku/v2/node/jsonrpc/message.nim
  waku/v2/node/jsonrpc/relay/callsigs.nim
  waku/v2/node/jsonrpc/relay/client.nim
  waku/v2/node/jsonrpc/relay/handlers.nim
  waku/v2/node/jsonrpc/relay/types.nim
  waku/v2/node/jsonrpc/store/handlers.nim
  waku/v2/node/jsonrpc/store/types.nim
  waku/v2/node/rest/base64.nim
  waku/v2/node/rest/relay/types.nim
Labels: track:production

#1563 feat(protobuf): added error wrappers for invalid length validation
  tests/all_tests_common.nim
  tests/common/test_protobuf_validation.nim
  tests/v2/test_waku_noise_sessions.nim
  waku/common/protobuf.nim
  waku/v2/protocol/waku_filter/rpc_codec.nim
  waku/v2/protocol/waku_lightpush/rpc_codec.nim
  waku/v2/protocol/waku_message/codec.nim
  waku/v2/protocol/waku_message/message.nim
  waku/v2/protocol/waku_store/rpc_codec.nim
Labels: track:production

#1572 fix(jsonrpc): use padded-base64 for payload encoding
  tests/common/test_base64_codec.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim
  tests/v2/wakunode_rest/test_rest_relay.nim
  tests/v2/wakunode_rest/test_rest_relay_serdes.nim
  waku/common/base64.nim
  waku/v2/node/jsonrpc/message.nim
  waku/v2/node/jsonrpc/relay/handlers.nim
  waku/v2/node/rest/base64.nim
  waku/v2/node/rest/relay/types.nim
Labels: track:maintenance

#1573 refactor(relay): split the message id provider into a module
  waku/v2/protocol/waku_relay.nim
  waku/v2/protocol/waku_relay/message_id.nim
  waku/v2/protocol/waku_relay/protocol.nim
Labels: track:production

#1496 feat(rln-relay): group manager integration
  .gitignore
  apps/chat2/chat2.nim
  apps/wakunode2/wakunode2.nim
  tests/all_tests_v2.nim
  tests/v2/test_rln_group_manager_onchain.nim
  tests/v2/test_rln_group_manager_static.nim
  tests/v2/test_waku_rln_relay.nim
  tests/v2/test_waku_rln_relay_onchain.nim
  tests/v2/test_wakunode_rln_relay.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/conversion_utils.nim
  waku/v2/protocol/waku_rln_relay/group_manager/group_manager_base.nim
  waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim
  waku/v2/protocol/waku_rln_relay/group_manager/static/group_manager.nim
  waku/v2/protocol/waku_rln_relay/protocol_types.nim
  waku/v2/protocol/waku_rln_relay/rln_relay.nim
  waku/v2/protocol/waku_rln_relay/utils.nim
Labels: track:rlnp2p

#1569 chore: use base64 url safe encoding for noise
  waku/v2/protocol/waku_noise/noise_utils.nim
Labels: track:production
