Repository waku-org/nwaku, pull requests merged in 2023-03, with the labels that each got.

#1581 feat(message): added meta attribute to waku message
  waku/v2/protocol/waku_message/codec.nim
  waku/v2/protocol/waku_message/message.nim
Labels: track:production

#1585 chore(rln-relay): address laundry list of improvements
  tests/v2/test_waku_rln_relay.nim
  waku/v2/protocol/waku_keystore/protocol_types.nim
  waku/v2/protocol/waku_rln_relay/constants.nim
  waku/v2/protocol/waku_rln_relay/conversion_utils.nim
  waku/v2/protocol/waku_rln_relay/rln/wrappers.nim
Labels: track:maintenance

#1587 chore(rln-relay): move rln-relay test suite to own dir
  tests/all_tests_v2.nim
  tests/v2/test_rln_wrappers.nim
  tests/v2/test_web3.nim
  tests/v2/waku_rln_relay/test_rln_group_manager_onchain.nim
  tests/v2/waku_rln_relay/test_rln_group_manager_static.nim
  tests/v2/waku_rln_relay/test_waku_rln_relay.nim
  tests/v2/waku_rln_relay/test_wakunode_rln_relay.nim
  tests/v2/waku_rln_relay/utils.nim
Labels: track:maintenance, track:rlnp2p

#1586 feat(message): added waku message deterministic hashing
  tests/all_tests_v2.nim
  tests/v2/test_waku_message_digest.nim
  tests/v2/testlib/waku2.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_message/digest.nim
Labels: track:production

#1588 refactor(message): move namespacing utils to waku message module
  apps/wakubridge/message_compat.nim
  tests/all_tests_v2.nim
  tests/v2/test_namespacing_utils.nim
  tests/v2/test_waku_message_topics.nim
  tests/wakubridge/test_message_compat.nim
  waku/v2/protocol/waku_message.nim
  waku/v2/protocol/waku_message/codec.nim
  waku/v2/protocol/waku_message/digest.nim
  waku/v2/protocol/waku_message/message.nim
  waku/v2/protocol/waku_message/topics.nim
  waku/v2/utils/namespacing.nim
Labels: track:production

#1591 fix: clean and normalize module imports
  waku/v2/node/jsonrpc/admin/handlers.nim
  waku/v2/node/jsonrpc/debug/client.nim
  waku/v2/node/jsonrpc/debug/handlers.nim
  waku/v2/node/jsonrpc/filter/client.nim
  waku/v2/node/jsonrpc/filter/handlers.nim
  waku/v2/node/jsonrpc/message.nim
  waku/v2/node/jsonrpc/relay/client.nim
  waku/v2/node/jsonrpc/relay/handlers.nim
  waku/v2/node/jsonrpc/store/client.nim
  waku/v2/node/jsonrpc/store/handlers.nim
  waku/v2/node/jsonrpc/store/types.nim
  waku/v2/node/peer_manager/peer_manager.nim
  waku/v2/node/rest/debug/handlers.nim
  waku/v2/node/rest/debug/types.nim
  waku/v2/node/rest/relay/client.nim
  waku/v2/node/rest/relay/handlers.nim
  waku/v2/node/rest/relay/topic_cache.nim
  waku/v2/protocol/waku_swap/waku_swap.nim
Labels: track:production

#1589 feat(message): differentiate content and pubsub topic namespacing
  apps/wakubridge/message_compat.nim
  tests/v2/test_waku_message_topics.nim
  waku/v2/protocol/waku_message/topics.nim
  waku/v2/protocol/waku_message/topics/content_topic.nim
  waku/v2/protocol/waku_message/topics/parsing.nim
  waku/v2/protocol/waku_message/topics/pubsub_topic.nim
Labels: track:production

#1596 refactor(enr): node capabilities code clean up and reorganization
  apps/wakunode2/wakunode2.nim
  examples/v2/publisher.nim
  examples/v2/subscriber.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_enr.nim
  tests/v2/test_waku_peer_exchange.nim
  tools/networkmonitor/networkmonitor.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_discv5.nim
  waku/v2/protocol/waku_enr.nim
Labels: track:production

#1598 feat(common): added the enr builder
  tests/all_tests_common.nim
  tests/common/test_enr_builder.nim
  tests/v2/testlib/waku2.nim
  waku/common/enr.nim
  waku/v2/protocol/waku_enr.nim
Labels: track:production

#1599 feat(enr): added enr builder waku capabilities extension
  tests/common/test_enr_builder.nim
  tests/v2/test_waku_enr.nim
  waku/v2/protocol/waku_enr.nim
Labels: track:production

#1594 chore(rln-relay): msg validation according to new circuit
  tests/v2/waku_rln_relay/test_waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/conversion_utils.nim
  waku/v2/protocol/waku_rln_relay/protocol_types.nim
  waku/v2/protocol/waku_rln_relay/rln/wrappers.nim
  waku/v2/protocol/waku_rln_relay/rln_relay.nim
Labels: track:maintenance, track:rlnp2p

#1603 feat(rln-relay): fetch release from zerokit ci, or build
  .gitignore
  Makefile
  scripts/build_rln.sh
Labels: track:production, track:rlnp2p

#1618 feat(common): added enr typed record replacement
  tests/common/test_enr_builder.nim
  tests/v2/test_waku_enr.nim
  waku/common/enr.nim
  waku/common/enr/builder.nim
  waku/common/enr/typed_record.nim
  waku/v2/protocol/waku_enr.nim
Labels: track:production

#1619 refactor(enr): added waku2 capabilities accessor
  tests/v2/test_waku_enr.nim
  waku/v2/protocol/waku_enr.nim
Labels: track:production

#1627 fix(rln-relay): on chain registration
  waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim
  waku/v2/protocol/waku_rln_relay/rln/wrappers.nim
Labels: track:rlnp2p

#1628 fix(wakunode2): fix main warnings and drop swap support
  apps/chat2/chat2.nim
  apps/chat2/config_chat2.nim
  apps/wakunode2/config.nim
  apps/wakunode2/wakunode2.nim
Labels: track:maintenance

#1625 refactor(enr): move waku enr multiaddr to typedrecod and builder extensions
  examples/v2/publisher.nim
  examples/v2/subscriber.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_enr.nim
  tests/v2/test_waku_peer_exchange.nim
  waku/v2/protocol/waku_discv5.nim
  waku/v2/protocol/waku_enr.nim
Labels: track:production
