Repository waku-org/nwaku, pull requests merged in 2023-11, with the labels that each got.

#2186 feat: discv5 filter peer by capability
  tests/test_waku_discv5.nim
  waku/waku_discv5.nim
Labels: E:1.4: Sharded peer management and discovery

#2210 chore: update docs for rln-keystore-generator
  Makefile
  docs/tutorial/rln-keystore-generator.md
  waku.nimble
Labels: track:rln

#2187 chore: improving node setup w.r.t sharding information
  apps/wakunode2/app.nim
  examples/publisher.nim
  examples/subscriber.nim
  tests/test_peer_manager.nim
  tests/test_waku_discv5.nim
  tests/test_waku_peer_exchange.nim
  tests/testlib/wakunode.nim
  tests/wakunode2/test_app.nim
  waku/node/waku_node.nim
  waku/waku_discv5.nim
  waku/waku_metadata/protocol.nim
Labels: E:1.4: Sharded peer management and discovery

#2202 feat: Add new DB column `messageHash`
  migrations/message_store/00008_updatePrimaryKey_add_col.up.sql
  tests/waku_archive/test_driver_postgres.nim
  tests/waku_archive/test_driver_postgres_query.nim
  tests/waku_archive/test_driver_queue_query.nim
  tests/waku_archive/test_driver_sqlite.nim
  tests/waku_archive/test_driver_sqlite_query.nim
  tests/waku_archive/test_retention_policy.nim
  tests/waku_archive/test_waku_archive.nim
  tests/waku_core/test_message_digest.nim
  tests/waku_store/test_resume.nim
  tests/waku_store/test_wakunode_store.nim
  tests/wakunode_jsonrpc/test_jsonrpc_store.nim
  tests/wakunode_rest/test_rest_store.nim
  waku/node/waku_node.nim
  waku/waku_archive/archive.nim
  waku/waku_archive/driver.nim
  waku/waku_archive/driver/postgres_driver/postgres_driver.nim
  waku/waku_archive/driver/queue_driver/queue_driver.nim
  waku/waku_archive/driver/sqlite_driver/migrations.nim
  waku/waku_archive/driver/sqlite_driver/queries.nim
  waku/waku_archive/driver/sqlite_driver/sqlite_driver.nim
  waku/waku_core/message/digest.nim
  waku/waku_filter_v2/protocol.nim
  waku/waku_store/client.nim
Labels: release-notes

#2243 chore: refactoring peer storage
  tests/test_peer_storage.nim
  waku/node/peer_manager/peer_manager.nim
  waku/node/peer_manager/peer_store/peer_storage.nim
  waku/node/peer_manager/peer_store/waku_peer_storage.nim
Labels: E:1.4: Sharded peer management and discovery

#2221 chore(rest): improved message cache logic
  apps/chat2bridge/chat2bridge.nim
  apps/wakunode2/app.nim
  tests/test_message_cache.nim
  tests/wakunode_jsonrpc/test_jsonrpc_filter.nim
  tests/wakunode_jsonrpc/test_jsonrpc_relay.nim
  tests/wakunode_rest/test_rest_filter.nim
  tests/wakunode_rest/test_rest_legacy_filter.nim
  tests/wakunode_rest/test_rest_relay.nim
  waku/waku_api/handlers.nim
  waku/waku_api/jsonrpc/filter/handlers.nim
  waku/waku_api/jsonrpc/relay/handlers.nim
  waku/waku_api/message_cache.nim
  waku/waku_api/rest/filter/handlers.nim
  waku/waku_api/rest/filter/legacy_handlers.nim
  waku/waku_api/rest/relay/handlers.nim
Labels: E:1.2: Autosharding for autoscaling

#2251 feat: setting image deployment to harbor registry
  ci/Jenkinsfile.release
Labels: infra
