Repository waku-org/nwaku, pull requests merged in 2023-01, with the labels that each got.

#1481 feat(archive): respond with error on more than 10 content topics query
  tests/v2/waku_archive/test_waku_archive.nim
  waku/v2/protocol/waku_archive/archive.nim
  waku/v2/protocol/waku_archive/common.nim
Labels: track:production

#1494 fix(chat2): warn when rln relay is enabled but not compiled
  apps/chat2/chat2.nim
Labels: track:rln

#1465 feat(rln-relay): abstract group management into its own api
  .gitignore
  tests/v2/test_rln_group_manager_onchain.nim
  tests/v2/test_rln_group_manager_static.nim
  waku/v2/protocol/waku_rln_relay.nim
  waku/v2/protocol/waku_rln_relay/conversion_utils.nim
  waku/v2/protocol/waku_rln_relay/group_manager.nim
  waku/v2/protocol/waku_rln_relay/group_manager/group_manager_base.nim
  waku/v2/protocol/waku_rln_relay/group_manager/on_chain.nim
  waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim
  waku/v2/protocol/waku_rln_relay/group_manager/static.nim
  waku/v2/protocol/waku_rln_relay/group_manager/static/group_manager.nim
  waku/v2/protocol/waku_rln_relay/protocol_metrics.nim
  waku/v2/protocol/waku_rln_relay/rln.nim
  waku/v2/protocol/waku_rln_relay/rln/rln_interface.nim
  waku/v2/protocol/waku_rln_relay/rln/wrappers.nim
  waku/v2/protocol/waku_rln_relay/utils.nim
Labels: track:rln, track:maintenance

#1497 fix(rln-relay): use new credentials for compatibility
  waku/v2/protocol/waku_rln_relay/constants.nim
Labels: track:maintenance, track:rlnp2p

#1511 fix(archive): reverse the db query results in the waku archive front-end
  tests/v2/waku_archive/test_driver_queue_query.nim
  tests/v2/waku_archive/test_driver_sqlite_query.nim
  tests/v2/waku_archive/test_waku_archive.nim
  waku/v2/protocol/waku_archive/archive.nim
  waku/v2/protocol/waku_archive/driver/queue_driver/queue_driver.nim
  waku/v2/protocol/waku_archive/driver/sqlite_driver/sqlite_driver.nim
Labels: track:production

#1509 feat(wakunode): advertise custom multiaddresses
  apps/wakunode2/config.nim
  apps/wakunode2/wakunode2.nim
  tests/v2/test_wakunode.nim
  waku/v2/node/waku_node.nim
  waku/v2/utils/peers.nim
Labels: track:maintenance

#1515 refactor(tests): group waku store test suite files
  tests/all_tests_v2.nim
  tests/v2/waku_store/test_resume.nim
  tests/v2/waku_store/test_rpc_codec.nim
  tests/v2/waku_store/test_waku_store.nim
  tests/v2/waku_store/test_wakunode_store.nim
Labels: track:maintenance

#1517 fix(rln): remove kilic submodule
  .gitmodules
Labels: track:maintenance
