Repository waku-org/nwaku, pull requests merged in 2023-04, with the labels that each got.

#1645 fix: fixed multiple bare except warnings
  apps/wakubridge/wakubridge.nim
  apps/wakunode2/config.nim
  apps/wakunode2/wakunode2.nim
  tests/v2/waku_rln_relay/test_rln_group_manager_onchain.nim
  tools/networkmonitor/networkmonitor.nim
  tools/networkmonitor/networkmonitor_utils.nim
  waku/common/logging.nim
  waku/v2/node/rest/relay/types.nim
  waku/v2/protocol/waku_archive/driver/queue_driver/queue_driver.nim
  waku/v2/protocol/waku_filter/client.nim
  waku/v2/protocol/waku_keystore/keystore.nim
  waku/v2/protocol/waku_keystore/utils.nim
  waku/v2/protocol/waku_noise/noise_handshake_processing.nim
  waku/v2/protocol/waku_noise/noise_utils.nim
  waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim
Labels: track:maintenance

#1644 chore: remove deprecated enr record init method
  tests/v2/test_waku_enr.nim
  waku/v2/node/waku_node.nim
  waku/v2/protocol/waku_enr.nim
Labels: track:production

#1646 refactor(node): added waku_node barrel import and split config module
  apps/wakunode2/wakunode2.nim
  tests/v2/test_waku_discv5.nim
  tests/v2/test_waku_switch.nim
  waku/v2/node/README.md
  waku/v2/node/config.nim
  waku/v2/node/nim.cfg
  waku/v2/node/waku_node.nim
  waku/v2/node/waku_switch.nim
  waku/v2/waku_node.nim
Labels: track:maintenance

#1648 chore: pointed all waku node imports to the barrel import
  apps/chat2/chat2.nim
  apps/chat2bridge/chat2bridge.nim
  apps/wakubridge/wakubridge.nim
  apps/wakunode2/wakunode2_setup_rest.nim
  apps/wakunode2/wakunode2_setup_rpc.nim
  examples/v2/publisher.nim
  examples/v2/subscriber.nim
  tests/v2/test_peer_exchange.nim
  tests/v2/test_peer_manager.nim
  tests/v2/test_peer_store_extended.nim
  tests/v2/test_waku_dnsdisc.nim
  tests/v2/test_waku_keepalive.nim
  tests/v2/test_waku_peer_exchange.nim
  tests/v2/test_wakunode.nim
  tests/v2/test_wakunode_filter.nim
  tests/v2/test_wakunode_lightpush.nim
  tests/v2/waku_relay/test_wakunode_relay.nim
  tests/v2/waku_rln_relay/test_wakunode_rln_relay.nim
  tests/v2/waku_store/test_wakunode_store.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_admin.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_debug.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_filter.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_relay.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim
  tests/v2/wakunode_rest/test_rest_debug.nim
  tests/v2/wakunode_rest/test_rest_relay.nim
  tests/wakubridge/test_wakubridge.nim
  tools/networkmonitor/networkmonitor.nim
  tools/scripts/rpc_info.nim
  tools/scripts/rpc_publish.nim
  tools/scripts/rpc_query.nim
  tools/scripts/rpc_subscribe.nim
  tools/scripts/rpc_subscribe_filter.nim
  tools/simulation/quicksim2.nim
  tools/wakucanary/wakucanary.nim
  waku/waku.nim
Labels: track:maintenance

#1649 feat(node): added waku node builder type
  apps/chat2/chat2.nim
  apps/chat2bridge/chat2bridge.nim
  apps/wakubridge/wakubridge.nim
  apps/wakunode2/wakunode2.nim
  examples/v2/publisher.nim
  examples/v2/subscriber.nim
  tools/networkmonitor/networkmonitor.nim
  tools/networkmonitor/networkmonitor_utils.nim
  tools/wakucanary/wakucanary.nim
  waku/v2/node/builder.nim
  waku/v2/utils/peers.nim
  waku/v2/waku_node.nim
Labels: track:production, track:maintenance

#1653 fix(wakunode2): made setup nat return errors
  apps/wakunode2/wakunode2.nim
  waku/common/utils/nat.nim
Labels: track:production

#1655 refactor(wakunode2): split setup logic into app module (pt. 1)
  apps/wakunode2/app.nim
  apps/wakunode2/wakunode2.nim
Labels: track:maintenance

#1656 refactor(wakunode2): split setup logic into app module (pt. 2)
  apps/wakunode2/app.nim
  apps/wakunode2/wakunode2.nim
Labels: track:maintenance

#1657 refactor(wakunode2): split setup logic into app module (pt. 3)
  apps/wakunode2/app.nim
  apps/wakunode2/wakunode2.nim
Labels: track:maintenance

#1659 refactor(wakunode2): split setup logic into app module (pt. 4)
  apps/wakunode2/app.nim
  apps/wakunode2/wakunode2.nim
Labels: track:maintenance

#1663 fix: wrap untracked protocol handler exceptions
  waku/v2/protocol/waku_lightpush/protocol.nim
  waku/v2/protocol/waku_store/protocol.nim
Labels: track:maintenance

#1672 fix(rln-relay): scope of getEvents
  waku/v2/protocol/waku_rln_relay/group_manager/on_chain/group_manager.nim
Labels: track:rlnp2p

#1689 chore: add deprecation notice to utils module. move heartbeat to common
  waku/common/nimchronos.nim
  waku/common/utils/DEPRECATION_NOTICE.md
  waku/v2/node/peer_manager/peer_manager.nim
Labels: track:maintenance

#1691 fix(rest): change rest server result error type to string
  waku/v2/node/rest/server.nim
Labels: track:maintenance

#1688 chore(core): move utils time module to waku_core
  apps/chat2/chat2.nim
  apps/wakubridge/wakubridge.nim
  examples/v2/publisher.nim
  examples/v2/subscriber.nim
  tests/all_tests_v2.nim
  tests/v2/test_utils_compat.nim
  tests/v2/testlib/common.nim
  tests/v2/testlib/wakucore.nim
  tests/v2/waku_archive/test_driver_queue.nim
  tests/v2/waku_archive/test_driver_queue_index.nim
  tests/v2/waku_archive/test_driver_queue_pagination.nim
  tests/v2/waku_archive/test_retention_policy.nim
  tests/v2/waku_archive/test_waku_archive.nim
  tests/v2/waku_core/test_time.nim
  tests/v2/waku_store/test_rpc_codec.nim
  tests/v2/wakunode_jsonrpc/test_jsonrpc_store.nim
  tests/v2/wakunode_rest/test_rest_relay.nim
  tests/v2/wakunode_rest/test_rest_store.nim
  tools/simulation/quicksim2.nim
  waku/v2/node/jsonrpc/message.nim
  waku/v2/node/jsonrpc/relay/handlers.nim
  waku/v2/node/jsonrpc/store/client.nim
  waku/v2/node/jsonrpc/store/handlers.nim
  waku/v2/node/rest/store/handlers.nim
  waku/v2/node/rest/store/types.nim
  waku/v2/node/waku_node.nim
  waku/v2/waku_archive/archive.nim
  waku/v2/waku_archive/common.nim
  waku/v2/waku_archive/driver.nim
  waku/v2/waku_archive/driver/queue_driver/index.nim
  waku/v2/waku_archive/driver/queue_driver/queue_driver.nim
  waku/v2/waku_archive/driver/sqlite_driver/cursor.nim
  waku/v2/waku_archive/driver/sqlite_driver/queries.nim
  waku/v2/waku_archive/driver/sqlite_driver/sqlite_driver.nim
  waku/v2/waku_archive/retention_policy/retention_policy_time.nim
  waku/v2/waku_core.nim
  waku/v2/waku_core/message/codec.nim
  waku/v2/waku_core/message/message.nim
  waku/v2/waku_core/time.nim
  waku/v2/waku_rln_relay/rln/wrappers.nim
  waku/v2/waku_rln_relay/rln_relay.nim
  waku/v2/waku_store/common.nim
  waku/v2/waku_store/protocol.nim
  waku/v2/waku_store/rpc.nim
Labels: track:maintenance

#1694 build: decouple test2 target from testcommon
  Makefile
Labels: track:maintenance

#1690 refactor(wakunode2): split setup logic into app module
  .github/workflows/ci-experimental.yml
  .github/workflows/ci.yml
  Makefile
  apps/wakunode2/app.nim
  apps/wakunode2/wakunode2.nim
  apps/wakunode2/wakunode2_setup_rest.nim
  apps/wakunode2/wakunode2_setup_rpc.nim
  tests/all_tests_wakunode2.nim
  tests/wakunode2/test_app.nim
  waku.nimble
Labels: track:maintenance

#1705 refactor(wakunode2): flatten and simplify app setup
  apps/chat2/chat2.nim
  apps/wakunode2/app.nim
  apps/wakunode2/wakunode2_setup_rest.nim
  apps/wakunode2/wakunode2_setup_rpc.nim
  waku/v2/node/waku_metrics.nim
Labels: track:production

#1706 chore: move networkmonitor and wakucanary to apps directory
  Makefile
  apps/networkmonitor/README.md
  apps/networkmonitor/networkmonitor.nim
  apps/networkmonitor/networkmonitor_config.nim
  apps/networkmonitor/networkmonitor_metrics.nim
  apps/networkmonitor/networkmonitor_utils.nim
  apps/networkmonitor/nim.cfg
  apps/wakucanary/README.md
  apps/wakucanary/nim.cfg
  apps/wakucanary/wakucanary.nim
  tools/README.md
  tools/scripts/rpc_info.nim
  tools/scripts/rpc_publish.nim
  tools/scripts/rpc_query.nim
  tools/scripts/rpc_subscribe.nim
  tools/scripts/rpc_subscribe_filter.nim
  tools/simulation/quicksim2.nim
  tools/simulation/start_network2.nim
  waku.nimble
Labels: track:maintenance
