Repository waku-org/nwaku, pull requests merged in 2024-08, with the labels that each got.

#2947 chore: optimizations for discv5 only nodes
  examples/wakustealthcommitments/node_spec.nim
  waku/factory/external_config.nim
  waku/factory/node_factory.nim
  waku/factory/waku.nim
Labels: release-notes

#2941 chore: replace statusim.net instances with status.im
  apps/wakucanary/README.md
  docs/benchmarks/postgres-adoption.md
  docs/faq.md
  docs/operators/how-to/configure-store-v0.12.0.md
  docs/operators/how-to/configure-store.md
  docs/tutorial/chat2.md
  examples/filter_subscriber.nim
  examples/lightpush_publisher.nim
  tests/test_waku_enr.nim
Labels: infra

#2983 chore: deprecating protected topics in favor of protected shards
  tests/wakunode2/test_validators.nim
  waku/factory/external_config.nim
  waku/factory/node_factory.nim
  waku/factory/validator_signed.nim
Labels: release-notes

#2991 fix: copy libnegentropy.so from nim-build image
  Dockerfile
Labels: bug, infra
